from __future__ import annotations

from enum import Enum


class NegeriEnum(str, Enum):
    JOHOR = "JOHOR"
    KEDAH = "KEDAH"
    KELANTAN = "KELANTAN"
    MELAKA = "MELAKA"
    NEGERI_SEMBILAN = "NEGERI_SEMBILAN"
    PAHANG = "PAHANG"
    PERAK = "PERAK"
    PERLIS = "PERLIS"
    PULAU_PINANG = "PULAU_PINANG"
    SABAH = "SABAH"
    SARAWAK = "SARAWAK"
    SELANGOR = "SELANGOR"
    TERENGGANU = "TERENGGANU"
    WILAYAH_PERSEKUTUAN_KUALA_LUMPUR = "WILAYAH_PERSEKUTUAN_KUALA_LUMPUR"
    WILAYAH_PERSEKUTUAN_LABUAN = "WILAYAH_PERSEKUTUAN_LABUAN"
    WILAYAH_PERSEKUTUAN_PUTRAJAYA = "WILAYAH_PERSEKUTUAN_PUTRAJAYA"
